[tool.black]
target-version = ["py311"]

[tool.mypy]
packages = "b3"
ignore_errors = true

[tool.ruff]
target-version = "py311"
extend-exclude = [".*"]
select = [
#    "A",  # shadowing builtins
#    "ARG",  # unused arguments
    "B",  # bugbear
    "C40",  # comprehensions
    "DTZ",  # checks for naive datetimes
    "E",  # pycodestyle (errors)
#    "ERA",  # eradicate (commented out code)
    "F",  # Pyflakes
#    "FBT",  # boolean trap
    "I",   # isort
    "ISC",  # Implicit String Concat
#    "N",  # pep8-naming
    "PIE",  # misc lints
#    "PL",  # Pylint
#    "PTH",  # favor pahtlib.Path
#    "RET",  # returns
    "RUF",  # Ruff-specific rules
    "S",  # bandit
    "SIM",  # simplify
#    "T20",  # print statements
#    "TRY",  # tryceratops
    "UP",  # pyupgrade
    "W",  # pycodestyle (warnings)
]
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"b3/plugins/hof.py" = ["S608"]  # Possible SQL Injection
"b3/storage/*" = ["S608"]  # Possible SQL Injection
"tests/*" = [
    "S101",  # Use of assert
    "S106",  # Possible hardcoded password
]
